version: '3.0'

services:
  ci-compose:
    container_name: ci-compose
    image: tactless/ci-compose:test
    ports:
      - 3030:3000
    depends_on:
      - database
  database:
    image: mongo:3.6
    container_name: database
    ports:
      - 27017:27017
