version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - run: npm install
      - setup_remote_docker
      - run: docker build -t tactless/ci-compose:test .
      - run: docker-compose up -d
      - run: docker build -f Dockerfile-test -t tactless/ci-compose-tests:test .
      - run: docker run --network tactless/ci-compose-tests:test
      # - run:
      #     name: Start container and verify it's working
      #     command: |
      #       set -x
      #       docker-compose up -d
      #       # docker-compose will start 2 containers, the one with service will be named `contacts`
      #       # we start another container with curl in the same network as `contacts`, this way we have
      #       # all exposed ports from `contacts` available on `localhost` in this new container
      #       docker run --network container:ci-compose \
      #         appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/
      # - run: docker ps
      # - run: npm test
workflows:
  version: 2
  workflow:
    jobs:
      - build
